-- Migration: Create AI-generated tasks table
-- Description: Store tasks generated by AI from SPINE events
-- Date: 2026-01-14

-- Create ai_tasks table
CREATE TABLE IF NOT EXISTS ai_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id UUID REFERENCES spine_events(id) ON DELETE CASCADE,
  workspace_id UUID,
  title VARCHAR(500) NOT NULL,
  description TEXT,
  priority VARCHAR(20) NOT NULL CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_progress', 'completed', 'cancelled')),
  due_date TIMESTAMPTZ,
  assigned_to UUID,
  model VARCHAR(50),
  confidence_score DECIMAL(3,2),
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_ai_tasks_event_id ON ai_tasks(event_id);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_workspace_id ON ai_tasks(workspace_id);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_status ON ai_tasks(status);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_priority ON ai_tasks(priority);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_due_date ON ai_tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_ai_tasks_assigned_to ON ai_tasks(assigned_to);

-- Add comment
COMMENT ON TABLE ai_tasks IS 'Tasks generated by AI from SPINE events';
COMMENT ON COLUMN ai_tasks.event_id IS 'Reference to the SPINE event that generated this task';
COMMENT ON COLUMN ai_tasks.model IS 'AI model used to generate the task (e.g., gpt-4o, claude-3)';
COMMENT ON COLUMN ai_tasks.confidence_score IS 'Confidence score from AI (0.00 to 1.00)';
